CC=clang
CFLAGS= -Wall -Wextra -Werror

all: Makefile Sully Grace Colleen

Colleen: Colleen.c
	$(CC) $(CFLAGS) -o Colleen Colleen.c

Grace: Grace.c
	$(CC) $(CFLAGS) -o Grace Grace.c

Sully: Sully.c
	$(CC) $(CFLAGS) -o Sully Sully.c

